version: '3'
services:

  juzt-app:
    image: php:7.3.7-fpm
    container_name: juzt-app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - juzt-db
    env_file:
      - .env
    working_dir: /var/www
    command: "php artisan serve --host=0.0.0.0 --port=80"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
    environment:
      VIRTUAL_HOST: ${APP_DOMAIN_NAME}

  juzt-db:
    image: mariadb:latest
    container_name: juzt-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - juzt-database:/var/lib/mysql/

  juzt-adminer:
    image: adminer:latest
    env_file:
      - .env
    container_name: juzt-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: juzt-db
      ADMINER_DEFAULT_DB_NAME: homestead
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    volumes:
      - ./:/www
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - juzt-db

volumes:
  juzt-database:
    driver: local
