version: '3'
services:

  juzt-app:
    image: php:7.3.7-fpm
    container_name: juzt-app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - juzt-db
    env_file:
      - .env
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
    environment:
      VIRTUAL_HOST: ${APP_DOMAIN_NAME}
    networks:
      - juzt-network

  juzt-db:
    image: mariadb:latest
    container_name: juzt-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - juzt-data:/var/lib/mysql/
    networks:
      - juzt-network

  juzt-adminer:
    image: adminer:latest
    env_file:
      - .env
    container_name: juzt-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: maria
      ADMINER_DEFAULT_DB_NAME: homestead
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    volumes:
      - ./:/www
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - juzt-db
    networks:
      - juzt-network


networks:
  juzt-network:
    driver: bridge

volumes:
  juzt-data:
    driver: local